### ISSUE TITLE
Funders area needs conceptualisation

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS-Website#125]

**Comment by anitagraser** [comment]
Latest discussions include: Asking sustaining members to provide monochrome logos of a certain size if they want to be listed on the front page. This could be implemented in the form of another file upload in the member area of [Projecta](https://changelog.qgis.org/en/qgis/sponsorship-programme/).

**Comment by timlinux** [comment]
This is taken care of in the new implementation.

![image](https://github.com/qgis/QGIS-Hugo/assets/178003/88b3e19b-f73e-46c0-9042-9c37d9c1f33d)
