### ISSUE TITLE
Implement Figma Design

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS-Website#135]
### Feature Description

This is the consolidated draft design based on the community feedback, created at the Contributor Meeting 2023: https://www.figma.com/proto/1jFYgq9R5nwHChf4HhhHpW/QGIS-(Copy)?node-id=301-1657&scaling=scale-down-width&page-id=301%3A299

Next, we need to create the building blocks in Bulma. 

![Design 1](https://user-images.githubusercontent.com/590385/233774677-a371a0f7-d490-4dfd-bcb2-ecd217d7f1e2.jpg)

**Comment by timlinux** [comment]
I think this is out of date now, closing.
