### ISSUE TITLE
Wording during pricing selection

### ISSUE THREAD

**Issue by rosaguilar** [qgis/QGIS-Website#136]
### Feature Description

Add education, e.g., universities and other users such as NGOs when choosing the pricing type.
Such institutions are not included in the current mock-up ( pricing options) 

### Reference to Feature

![image](https://user-images.githubusercontent.com/590385/233787124-83a3d603-a4fb-44cc-98f5-005cf0966496.png)

**Comment by timlinux** [comment]
Dear @rosaguilar

Thank you so much for the inputs you gave here. In the end we have gone a different route here:

![image](https://github.com/qgis/QGIS-Hugo/assets/178003/4ca74ded-3815-4d6b-962b-f906ed1a2240)


Its clean and simple and I think it is ok for now....
