### ISSUE TITLE
Trusted by logos marquee

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS-Website#144]
### Summary

![image](https://github.com/qgis/QGIS-Hugo/assets/178003/1386da90-4c11-496d-93e7-97dc37ae53fc)

**Comment by timlinux** [comment]
Can you take this @Xpirix ?

**Comment by Xpirix** [comment]
Sure, I will add it to my work planning.

**Comment by Xpirix** [comment]
Hi @timlinux , I see that the "Trusted by" block doesn't exist anymore on the current version.

**Comment by timlinux** [comment]
Ok let's park it for now thanks
