### ISSUE TITLE
Suggestion for the documentation link

### ISSUE THREAD

**Issue by Xpirix** [qgis/QGIS-Website#218]
### Feature Description

From Bourdon, Jean-François (DIF) <Jean-Francois.Bourdon@mrnf.gouv.qc.ca>

> Hi Lova,

> If I’m not mistaken, you are the person working on the new QGIS website. I’ve taken a look at the new website and I would have a few suggestion to make about the “QGIS resources” page (https://qgis.github.io/QGIS-Hugo/resources/hub/).
 
> First, I must say that your work is great! More modern, cleaner, I’m all for it! 😊
 
> My issue is with the menu on the left. Under “Resources”, there is the element “Documentation” which point to an external website (https://docs.qgis.org/latest/en/docs/index.html) but at the same time the first sub-section of the Resources/QGIS resources is also named “Documentation”. It’s a bit confusing considering that none of the links provided in this section (Desktop User Guide/Manual, Server Guide/Manual, QGIS Training manual, Documentation Guidelines [dead link], Introduction in GIS, PyQGIS cookbook, etc.) lead to website linked by “Documentation” in the left pane (https://docs.qgis.org/latest/en/docs/index.html). However, the reverse is true and all these links are present at https://docs.qgis.org/latest/en/docs/index.html.

  
![Picture1](https://github.com/qgis/QGIS-Hugo/assets/43842786/af585c45-e074-438c-9a7b-7c0be56a633b)

> I would then suggest the following:
 
![Picture2](https://github.com/qgis/QGIS-Hugo/assets/43842786/157c65e9-a553-4dea-820c-c100a198b3f2)

> I hope I managed to explain my thoughts clear enough with the screenshots…
 
> Thanks a lot for your hard work on the website, it will definitively improve the experience for new QGIS users.
 
> Regards,

**Comment by Xpirix** [comment]
Thank you for your interest in the new website and your suggestion. I believe that the credit for the great work goes to those who contributed to the QGIS-Hugo website, as well as to Kontur.

**Comment by timlinux** [comment]
Thank you very much for your suggestion Jean, the page now looks like this (see https://github.com/qgis/QGIS-Hugo/pull/263):

![image](https://github.com/qgis/QGIS-Hugo/assets/178003/0e785a9e-69c2-441d-82b0-8029d9ea135b)
