### ISSUE TITLE
Broken main menu links in "Project" entry

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS-Website#221]
### URL

https://qgis.github.io/QGIS-Hugo/project/overview

### Summary

https://qgis.github.io/QGIS-Hugo/project/overview is broken
![image](https://github.com/qgis/QGIS-Hugo/assets/590385/079db030-1e29-4bf7-a17e-1587430447d5)

Should be https://qgis.github.io/QGIS-Hugo/product/overview/ instead

**Comment by Xpirix** [comment]
I've made the change from https://github.com/qgis/qgis-uni-navigation. The links should be fixed now.

**Comment by anitagraser** [comment]
Looks good, thanks

**Comment by anitagraser** [comment]
Before closing this, please change "Product" to "Project" in the menu on the left in order to be consistent

![image](https://github.com/qgis/QGIS-Hugo/assets/590385/095fa138-529b-4020-acf3-24017922845e)

**Comment by anitagraser** [comment]
We discussed this in yesterday's PSC meeting and "project" is preferred over "product". So, ideally, the URLs should reflect this, e.g.

https://qgis.github.io/QGIS-Hugo/project 

instead of 

https://qgis.github.io/QGIS-Hugo/product

**Comment by Xpirix** [comment]
Thanks for the review. I've changed `Project` to `Product` in the navigation bar. We may need to clear the browser cache to see the change

![image](https://github.com/qgis/QGIS-Hugo/assets/43842786/0f6939a3-dbf4-4c09-9027-894803adac1d)

**Comment by timlinux** [comment]
@Xpirix this is the reverse of what we want: All references in the site and e2e tests should be to 'project'. So just globally replace all uses of Product with Project please.

**Comment by Xpirix** [comment]
Ah, I see. Thanks @timlinux. I will do it.

**Comment by Xpirix** [comment]
Please find the proposed changes at #241.

Regards
