### ISSUE TITLE
Process and analyze needs updated info

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS-Website#222]
### URL

https://qgis.github.io/QGIS-Hugo/product/overview/

### Summary

The Screenshot should show the new Temporal Controller and the number of algorithms should be filled in:

![image](https://github.com/qgis/QGIS-Hugo/assets/590385/faaac4f2-4ec2-4189-8684-f22ac7949e1d)

**Comment by timlinux** [comment]
Note link now at https://qgis.github.io/QGIS-Hugo/project/overview/ ... and I guess somebody wants the time manager to live on :-P
