### ISSUE TITLE
In-page anchor link jump too far down

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS-Website#223]
### URL

https://qgis.github.io/QGIS-Hugo/community/involve/#report-bugs

### On what type of device(s) did you see this bug?

Desktop

### Other Browser

Vivaldi

### Summary

When I click on the link, the page jumps down but it jumps too far, so that the selected section header is hidden behind the top menu bar

![qgis-hugo-bug1](https://github.com/qgis/QGIS-Hugo/assets/590385/536a5f97-4ba4-4e02-9e5b-4f494f044782)

**Comment by Xpirix** [comment]
Please find the proposed fix for this at #237.

Regards.
