### ISSUE TITLE
Negative values in roadmap timer

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS-Website#224]
### URL

https://qgis.github.io/QGIS-Hugo/resources/roadmap/

### On what type of device(s) did you see this bug?

Desktop

### Other Browser

Vivaldi

### Summary

I assume these values should always be positive: 
![image](https://github.com/qgis/QGIS-Hugo/assets/590385/dc911616-3a37-4efe-8013-2b6f14eae5bd)

**Comment by Xpirix** [comment]
Please find the proposed fix for this at #247.

Regards
