### ISSUE TITLE
Put link to main download page on top of the installation guide

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS-Website#227]
### URL

https://qgis.github.io/QGIS-Hugo/resources/installation-guide/

### Summary

Put link to https://qgis.github.io/QGIS-Hugo/download/ at the top where it's easily found

![image](https://github.com/qgis/QGIS-Hugo/assets/590385/219cd427-9e2a-43e5-a6e9-1f4c3a9ebc1e)

**Comment by Xpirix** [comment]
Please find the proposed fix for this at #239.

Regards.
