### ISSUE TITLE
Boxes overlap on narrow screens

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS-Website#231]
### URL

https://qgis.github.io/QGIS-Hugo/funding/membership/#your-benefits

### On what type of device(s) did you see this bug?

Desktop

### Other Browser

Vivaldi

### Summary

On narrow screens (before the theme changes to mobile phone mode) the boxes overlap: 
![image](https://github.com/qgis/QGIS-Hugo/assets/590385/3b418ca9-2d88-4f7a-a951-1bedcc7d2fa5)

**Comment by Xpirix** [comment]
Please find the proposed PR for this at #243.

Regards
