### ISSUE TITLE
Remove black image border

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS-Website#232]
### URL

https://qgis.github.io/QGIS-Hugo/community/involve/#qgis-documentation

### Summary

I think the page would look better if the documentation screenshots didn't have a black border 
![image](https://github.com/qgis/QGIS-Hugo/assets/590385/886e7126-998c-4fc1-88ca-6e670ebe75b4)

**Comment by Xpirix** [comment]
Please find the proposed PR for this at #242 

Regards.
