### ISSUE TITLE
Remove Twitter

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS-Website#234]
### URL

https://qgis.github.io/QGIS-Hugo/community/organisation/infrastructure/

### Summary

Since we've left Twitter, this should be replaced by the new Mastodon account https://fosstodon.org/@qgis

![image](https://github.com/qgis/QGIS-Hugo/assets/590385/6b81764c-3449-4414-b9c9-423c74e155fb)

**Comment by Xpirix** [comment]
Please find the proposed PR at #245

Regards.
