### ISSUE TITLE
Resolve empty boxes in brand guidelines page

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS-Website#235]
### URL

https://qgis.github.io/QGIS-Hugo/community/organisation/guidelines/

### Summary

Is something missing here? 

![image](https://github.com/qgis/QGIS-Hugo/assets/590385/03c3a9af-94f6-4d2d-8eed-9b35bf76f869)

**Comment by timlinux** [comment]
For me they render fine: 
![image](https://github.com/qgis/QGIS-Hugo/assets/178003/506b4823-3dba-4671-bc8a-71df771c1462)
Please re-open if you still see the issue...
