### ISSUE TITLE
Fix animation

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS-Website#31]
### URL

https://qgis.github.io/QGIS-Hugo/about/

### On what type of device(s) did you see this bug?

Desktop

### On which browser(s) are you seeing the problem?

Chrome

### Summary

The current bouncing animations are distracting.

Nicer animations are, for example:

* https://zoneatlas.com/fi/tuotteet/zoneatlas-discover-tee-oma-interaktiivinen-kartta/ : when you scroll down, you can see items slide in from the left. This sliding animation only happens the first time the visitor scrolls down the page

**Comment by timlinux** [comment]
Animations disabled for now...
