### ISSUE TITLE
Style .htaccess / apache listings

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS-Website#318]
### Feature Description

This makes me sad:
![image](https://github.com/qgis/QGIS-Hugo/assets/178003/cce5a1c5-3106-4237-9e33-762817b050be)

We can do this to make these pages brand aligned:

https://github.com/inasafe/data.inasafe.org/blob/master/docker/default.apache.conf

https://github.com/inasafe/data.inasafe.org/tree/master/resources

Candidates for this treatment:

https://docs.qgis.org/3.34/pdf/ (all versions)
https://download.qgis.org/downloads/
![image](https://github.com/qgis/QGIS-Hugo/assets/178003/1d1a4651-a43e-4042-b288-724fe462f3c4)

**Comment by Xpirix** [comment]
@timlinux , please find below the proposed theme for the directory listing:

![Image](https://github.com/user-attachments/assets/efde91eb-db4d-408e-a4c7-c081b5921204)

Please see the repo at https://github.com/Xpirix/QGIS-apache-directory-listing for more details.

**Comment by Xpirix** [comment]
Please find below the screenshot after change the links color:

![](https://github.com/Xpirix/QGIS-apache-directory-listing/blob/main/media/light-mode.png?raw=true)

**Comment by timlinux** [comment]
@jef-n can we get some help from you to deploy this?
