### ISSUE TITLE
Information about the Project Organisation / Community Voting Members is not up to date

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Website#337]
### URL

https://www.qgis.org/community/organisation/#community-voting-members

### Summary

The info in the [Community Voting Members](https://www.qgis.org/en/site/getinvolved/governance/governance.html#community-voting-members) section (perhaps other ones?) are not up to date.
The name of the OSGEO representative voting member is also not mentioned.

See  https://github.com/qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one/issues/1160, https://github.com/qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one/pull/1235.

**Comment by mbernasocchi** [comment]
@agiudiceandrea I allowed myself to fix the links to the issues.
