### ISSUE TITLE
Signals missing from TOC for QgisInterface

### ISSUE THREAD

**Issue by bogind** [qgis/QGIS-Website#349]
### URL

https://qgis.org/pyqgis/master/gui/QgisInterface.html

### On what type of device(s) did you see this bug?

Desktop

### On which browser(s) are you seeing the problem?

Firefox

### Summary

The signals list is missing from the [`QgisInterface`](https://qgis.org/pyqgis/master/gui/QgisInterface.html) class python API documentation.  
This appears to happen in older versions of the documentation as well, see below for 3.34, the detailed information starts right after the list of methods.

![image](https://github.com/user-attachments/assets/4a63675c-0f35-4447-b1d8-a95ce9ab2ff8)

The signals themselves still appear with detailed information, and can still be accessed via anchors, for example [https://qgis.org/pyqgis/master/gui/QgisInterface.html#qgis.gui.QgisInterface.currentLayerChanged](https://qgis.org/pyqgis/master/gui/QgisInterface.html#qgis.gui.QgisInterface.currentLayerChanged) still leads to the signal details.

The same issue happens on [QgsMapCanvas](https://qgis.org/pyqgis/master/gui/QgsMapCanvas.html), and I cannot remember if spotted in other pages as well, but I can confirm that the lists appeared in the master and 3.34 pages last week.

**Comment by timlinux** [comment]
Can you move this request to the relevant repo please? https://github.com/qgis/pyqgis-api-docs-builder

Seems you already have a ticket there for it.

https://github.com/qgis/pyqgis-api-docs-builder/issues/147

Thanks!
