### ISSUE TITLE
Implement search functionality

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS-Website#35]
### Feature Description

Please read the hugo docs on how to wire up search and implement using the bulma search box already provided.

**Comment by timlinux** [comment]
@rcoffie when you reach block state, you must please describe what you have tried, what you are stuck with so that one of your team mates can look into the issue - perhaps it is just something simple we can help you to move past.

Also provide a link to your work in progress branch.

**Comment by timlinux** [comment]
@rcoffie which strategy are you using btw? I suggest to follow this:

https://gist.github.com/eddiewebb/735feb48f50f0ddd65ae5606a1cb41ae

Why? Because we want to avoid adding any dependencies on node/grunt etc.

Take another 2 hours and see if you can get the above working, if not, check in with me....

**Comment by timlinux** [comment]
Make sure to read all the discussion around the above GIST - near the end some folks have synthesised the tweaks and improvements e.g. 

https://www.softwarecraftsperson.com/posts/2021-05-01-client-side-search-fuse/

and 

https://makewithhugo.com/add-search-to-a-hugo-site/

**Comment by rcoffie** [comment]
> @rcoffie when you reach block state, you must please describe what you have tried, what you are stuck with so that one of your team mates can look into the issue - perhaps it is just something simple we can help you to move past.
> 
> Also provide a link to your work in progress branch.

@timlinux well noted

**Comment by rcoffie** [comment]
@timlinux  
Search page rendering no matches found 

![no match found2](https://user-images.githubusercontent.com/34107104/209318920-8d17372f-200d-45ae-bf65-c14645bfbe04.png)

**Comment by rcoffie** [comment]
@timlinux  Search showing result now, left with styling the search box 
![search ok](https://user-images.githubusercontent.com/34107104/209333350-6d2dd989-6598-4276-8b19-8dfd4df831de.png)

**Comment by rcoffie** [comment]
@timlinux  done , please review when you are less busy
