### ISSUE TITLE
Redundant information from https://api.qgis.org/api/

### ISSUE THREAD

**Issue by velle** [qgis/QGIS-Website#357]
### Feature Description

Thanks to all of you for the new website. So far I find it much easier to navigate and much more pleasing :)

I did notice a few bits of redundant information, that IMO should be removed. I believe they are not exactly in the QGIS-Hugo project/repo, but rather part of the main code repo. But I feel the discussion/decision still belongs here, together with the new website. 

**Python C++ API, redundant info**
Most of the information on the main page of the API (generated by Doxygen) seems redundant, and can be found on more relevant pages of the qgis.org. 

See this https://api.qgis.org/api/3.28/. (screenshot at: https://imgur.com/a/UJ6nX5B)

**Python QGIS API, redundant info**

The same goes for the Python QGIS API, at https://qgis.org/pyqgis/master/, at least the sections:
 - introduction
 - communication channels
 - bug reporting

**Comment by timlinux** [comment]
Kindly refer you to https://github.com/qgis/pyqgis-api-docs-builder/issues for issues related to python docs.

@jef-n what iss the best way to report API issues since https://github.com/qgis/api.qgis.org is read only it seems
