### ISSUE TITLE
Follow Figma version 2 layout

### ISSUE THREAD

**Issue by anniinaiikkanen** [qgis/QGIS-Website#36]
### Summary

At the moment, the website is following more Figma version 1 layouts which were decided to be too busy and it has problems with UX. Make **a proper skeleton of that prototype** before adding any other elements or clutter to the page.

**Comment by anitagraser** [comment]
I've started a ticket to resolve the block design issues #71 

Tim and I also had a chat that - in some areas - we probably won't be able to avoid an second-level menu. The solution approach we came up with (and Tim has prototyped it) is to add a second menu bar like here for the documentation page. 

I'd love to hear what you think and if you have alternative ideas to solve this issue

![image](https://user-images.githubusercontent.com/590385/210024605-61c56b3f-33d0-411a-ae20-1492cd9fa869.png)

**Comment by anniinakovalainen** [comment]
Second-level pages are totally okay. There's actually no need for that second level page banner - I would remove it. It is basically a needless clutter. The second level page title/header is an indicator enough for the user about where they're at in the site.

On that note, there should be distinction between selected and non-selected first and second level nav items. For example, if you've navigated to this doc page, the selected first level page "Resources" should be underlined or a different text color than others. And same with the drop down menu. That's usually enough of indication to the user about where the user's at in the site.

**Comment by anitagraser** [comment]
Thanks! The motivation was that the final site structure will require three page levels, e.g.

- Resources 
   - Documentation
      - User manual
      - PyQGIS cookbook 
      - more  (see https://qgis.org/en/docs/index.html)
   - Hub
      - Plugins
      - Styles
      - Models
      - more (see https://plugins.qgis.org/geopackages/?order_by=-upload_date&&is_gallery=true)

So when the visitor is on the User manual page, the top menu would highlight "Resources" and the second menu "Documentation" and the page title would be "User manual".

**Comment by anitagraser** [comment]
I've tried to sketch the documentation page and the user guide page. I'm assuming the user guide will stay in ReadTheDocs. ReadTheDocs has theme support but I don't know how flexible it is and how far we want to push it

![image](https://user-images.githubusercontent.com/590385/210058212-08624304-8c93-4049-8d46-b41856781d07.png)

**Comment by anitagraser** [comment]
Superseded by https://github.com/qgis/QGIS-Hugo/issues/135
