### ISSUE TITLE
Large page size.

### ISSUE THREAD

**Issue by BezBIS** [qgis/QGIS-Website#365]
### URL

https://qgis.org/

### On what type of device(s) did you see this bug?

Phone, Desktop

### On which browser(s) are you seeing the problem?

Firefox, Chrome

### Summary

The homepage has a very large file size, 6.38 MB when tested on Desktop Firefox, which will contribute to slow page loads, wasted bandwidth for users (especially on metred connections), and higher than necessary carbon emissions. This is primarily down to images, but also large CSS files etc.

## Some tool reports
- Google's PageSpeed Insights: https://pagespeed.web.dev/analysis/https-qgis-org/f0rpundqvl?form_factor=mobile
- Pingdom tools: https://tools.pingdom.com/#6437dde9f6400000
- Website carbon: https://www.websitecarbon.com/website/qgis-org/

**Comment by BezBIS** [comment]
I have no previous experience with Hugo, but would love to help with performance optimisations in my spare time. I would have to first learn some of the basics of Hugo, however.

**Comment by haubourg** [comment]
@BezBIS Thanks for raising the issue. @Xpirix , I have a few hours free tomorrow to convert most pictures to webp and do some cleanups of unused things. Tell me if you are already on this task.

**Comment by Xpirix** [comment]
Hi @haubourg , sure. I'm not working on this for the moment.

**Comment by timlinux** [comment]
Thanks @haubourg and @Xpirix we deployed your updates. There is still #364 which we can address in that ticket.

Testing after you changes, the size is 4.87mb

![image](https://github.com/user-attachments/assets/bc21eeb0-1813-43bd-837f-53b9fb2082b4)
