### ISSUE TITLE
Utilize QGIS brand book

### ISSUE THREAD

**Issue by anniinaiikkanen** [qgis/QGIS-Website#38]
### Summary

Eventhough the brand book needs work still, the colors and typography are already there decided. Utilize those in the website.
[QGIS Brand Book.pdf](https://github.com/qgis/QGIS-Hugo/files/10285347/QGIS.Brand.Book.pdf)

**Comment by timlinux** [comment]
We are using the correct fonts now and the brandbook colours are set in config.toml and we are using sass to build the css.
