### ISSUE TITLE
Make a better visibility of the sustaining memberships

### ISSUE THREAD

**Issue by Xpirix** [qgis/QGIS-Website#383]
### Feature Description

From @andreasneumann 

> Could we perhaps add a link in the "Community" menu to the sustaining membership program and to the list of sustaining members?"
Or at least add the "Funding" section to the top-level menu?
I also noticed that the visual changelogs on the new website don't list the sustaining members anymore. I know the long list of sustaining members can be annoying to the users, but at least add a paragraph with direct links to the sustaining members who make it possible to do bug fixes and the grant programme.

**Comment by andreasneumann** [comment]
Thank you - @Xpirix and @timlinux - it is much easier to find now - in the "Community" section.
