### ISSUE TITLE
Bad ubuntu signing key

### ISSUE THREAD

**Issue by TahomaSoft** [qgis/QGIS-Website#387]
### On what type of device(s) did you see this bug?

Desktop

### On which browser(s) are you seeing the problem?

Firefox

### Summary

I'm running into the problem below with ubuntu 24 and your repo signing key.

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://ubuntu.qgis.org/ubuntu noble InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D155B8E6A419C5BE
W: Failed to fetch https://qgis.org/ubuntu/dists/noble/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY D155B8E6A419C5BE
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by jef-n** [comment]
Not reproducable.  Did you add the keyring as instructed on https://qgis.org/resources/installation-guide/#debianubuntu ?

**Comment by TahomaSoft** [comment]
Hi Jürgen,

No, I was following these directions:
https://download.qgis.org/qgisdata/QGIS-Website/live/html/en/site/forusers/alldownloads.html#debian-ubuntu

I'll try the link you gave me.

Thanks,

Erik

**Comment by TahomaSoft** [comment]
The instructions for the link you provided work, thanks!

Please consider obliterating the wrong instructions I found from the QGIS website.

Thanks,

Erik

**Comment by jef-n** [comment]
> The instructions for the link you provided work, thanks!
> Please consider obliterating the wrong instructions I found from the QGIS website.

How did you find that old archive?  The instructions were essentially the same, just in a much older state.

**Comment by TahomaSoft** [comment]
It was the first thing that came up on my google searchSent from my iPhoneOn Aug 3, 2024, at 08:41, Jürgen Fischer ***@***.***> wrote:﻿

The instructions for the link you provided work, thanks!
Please consider obliterating the wrong instructions I found from the QGIS website.

How did you find that old archive?  The instructions were essentially the same, just in a much older state.
