### ISSUE TITLE
Regression in mobile rendering

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS-Website#392]
Hi @Xpirix it seems mobile is leaving a phantom scroll bar on widget over the content:

![image](https://github.com/user-attachments/assets/71372653-ffa5-430d-8f39-ff74f9b702c2)

**Comment by Xpirix** [comment]
@timlinux , Sorry, I couldn't reproduce the issue, not even on mobile. However, I noticed that the schedule table impacts the page width and creates an extra width. I wonder if it might be the reason for this issue. Please find the proposed fix at #396

**Comment by Xpirix** [comment]
It is related to the menu on mobile.

**Comment by Xpirix** [comment]
Please find the proposed fix at https://github.com/qgis/qgis-uni-navigation/pull/17. I hope it will fix the issue.
