### ISSUE TITLE
'Python error: Couldn't load plugin 'sentinel2_download' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by Nazeertaj** [qgis/QGIS-Website#393]
### On what type of device(s) did you see this bug?

Desktop

### Summary

I am trying to install an app and I get this message while installing the plugin. 'Python error: Couldn't load plugin 'sentinel2_download' due to an error when calling its classFactory() method. Also the QGIS new document page doesn't have the top section that usually has the x to close the app.

**Comment by timlinux** [comment]
I'm sorry this issue tracker is for the QGIS web site. Try asking your question on one of the user forums.

Regards 

Tim

**Comment by Nazeertaj** [comment]
Thank you for your response. I am struggling to reach someone who can
assist me in this matter. I tried for hours and still unable to . Could you
kindly direct me further?

Best regards

Nazeer Tajudeen

USGTF & U.S. KIDS Certified Golf Coach

U.S.Kids Golf Top 50 Golf Coaches 2024

WGTF Top 50 Golf Teachers Worldwide 2023

Intl. Advisory Committee Member

PCA - Professional Coaching Alliance Certified

IGPA (Intl. Golf Psychology Association)

IPGA International PGA Member

***@***.***

+255784888862

P.O. Box 12045,

Dar es Salaam, Tanzania
