### ISSUE TITLE
In "Get involved" page there are links to docs for QGIS 3.28

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Website#399]
### URL

https://qgis.org/community/involve/

### Summary

"How to write documentation" points to https://docs.qgis.org/3.28/en/docs/documentation_guidelines/
"How to translate QGIS" points to https://docs.qgis.org/3.28/en/docs/documentation_guidelines/do_translations.html
"Develop Python plugins" points to https://docs.qgis.org/3.28/en/docs/pyqgis_developer_cookbook/index.html
"Get set up for QGIS Core development" points to https://docs.qgis.org/3.28/en/docs/developers_guide/index.html

**Comment by DelazJ** [comment]
It might be good to use either `latest` which will always point to the LTR or `testing` (for master) instead of version number.

**Comment by Xpirix** [comment]
Hi @agiudiceandrea and @DelazJ, please find the proposed fix at #404.

Regards.
