### ISSUE TITLE
User group flags missing in Chrome-based browsers

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS-Website#401]
### URL

https://qgis.org/community/groups/

### On what type of device(s) did you see this bug?

Desktop

### On which browser(s) are you seeing the problem?

Chrome

### Other Browser

Vivaldi, Brave 

### Summary

Flags seem to be missing in Chrome: 

![image](https://github.com/user-attachments/assets/792bb5e4-01d9-41a3-87cc-99eb072b61a5)

They do work in Firefox:

![image](https://github.com/user-attachments/assets/0a07e5cb-8811-4766-9d41-f9700611af4d)

**Comment by Xpirix** [comment]
The PR #398 should also fix this issue.

Regards.

**Comment by anitagraser** [comment]
OK, closing this as duplicate
