### ISSUE TITLE
Confusing issue template in GH

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS-Website#402]
### Tools

GH issues

### Summary

I'm confused by the term "episode" in "For problems with an episode itself (links, sponsors, typos, etc)"

Is this on purpose? Or should it be "page" instead of "episode"? 

![image](https://github.com/user-attachments/assets/465e7d53-4cb3-4a6c-add6-794739a5c009)

**Comment by Xpirix** [comment]
Yes, I also think it should be `page`. I will review the template. Some of its contents are still related to the original one.

**Comment by Xpirix** [comment]
Please find the proposed fix at #405.

Regards.

**Comment by anitagraser** [comment]
Looks good, thanks Lova
