### ISSUE TITLE
Error in the Qgis log panel, then the QUICKSM 

### ISSUE THREAD

**Issue by Tshepo-Mokwaledi** [qgis/QGIS-Website#407]
![Screenshot 2024-08-14 112738](https://github.com/user-attachments/assets/3d56e06e-d496-4833-98ce-b1953f1b9aa6)
![Screenshot 2024-08-14 112738](https://github.com/user-attachments/assets/7a147bb8-8694-48ad-8439-d1e706280f15)

**Comment by agiudiceandrea** [comment]
@Tshepo-Mokwaledi the reported issue is related to the QuickOSM plugin, not the QGIS Website. Please close this issue report and report the issue to the QuickOSM plugin devs https://github.com/3liz/QuickOSM/issues.
