### ISSUE TITLE
Add GDPR info 

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS-Website#410]
### Feature Description

As far as I can see, the data protection section has not yet been migrated to the new website 

![Screenshot_20240816_005655_Firefox](https://github.com/user-attachments/assets/75e45a7a-391b-47bf-a989-b8edab1e2e9a)

### Reference to Feature

https://www2.qgis.org/en/docs/index.html#dataprotection

**Comment by Xpirix** [comment]
Hi @anitagraser , I've added a new tab to the documentation pages. Please see the proposed PR at #503
