### ISSUE TITLE
Broken link in "QGIS Trademark and brand guidelines" page

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Website#411]
### URL

https://www.qgis.org/community/organisation/guidelines/

### Summary

The [OAMI](https://oami.europa.eu/eSearch/#details/trademarks/012702643) link is no longer available.
See also that the trademark name at https://euipo.europa.eu/eSearch/#details/trademarks/017228222 is incorrectly "Qgis" instead of "QGIS".

**Comment by Xpirix** [comment]
Hi @agiudiceandrea , thank you for reporting this. The OAMI link should be removed through the PR #502.  I've also asked @timlinux about the trademark name on EUIPO.
