### ISSUE TITLE
https://issues.qgis.org/projects/qgis/ shows "Redmine 500 error"

### ISSUE THREAD

**Issue by velle** [qgis/QGIS-Website#422]
### URL

https://issues.qgis.org/projects/qgis/

### On what type of device(s) did you see this bug?

Desktop

### Summary

Entering https://issues.qgis.org/projects/qgis/ in browser, but instead of content an error message generated server side is shown. 

![image](https://github.com/user-attachments/assets/b1489ba4-a7c0-475f-a40a-1f12a68a44ca)

**Comment by Xpirix** [comment]
Thanks for reporting this @velle . Could you please confirm the origin of the link?
@timlinux Is this domain related to issue reporting? Should we update it to redirect to GitHub?

**Comment by velle** [comment]
> Thanks for reporting this @velle . Could you please confirm the origin of the link? @timlinux Is this domain related to issue reporting? Should we update it to redirect to GitHub?

Unfortunately I don't remember exactly, but I do remember the following:

I googled something, lets say "QGIS foobar", and I then selected the top 1 or 2 result on Google. That took me to some address, maybe https://issues.qgis.org/projects/qgis/foobar, which gave the same error. 

When I reported the issue, I left out the "most specific" part of the URL.

**Comment by velle** [comment]
I googled for "qgis gnu debugger" and the first result was at https://issues.qgis.org/projects/qgis/wiki/How_to_debug_QGIS_Plugins. 

![image](https://github.com/user-attachments/assets/c980c7c8-7dba-402a-9a13-7e26136da2c1)

**Comment by jef-n** [comment]
We used redmine for bugtracking before github - all the migrated tickets are linking there and vice versa - it's readonly and points at github on the frontpage.

**Comment by haubourg** [comment]
IMHO we should consider decommissioning the old redmine. I haven't had any need to dig back into the original issue that was copied in github for a great while; 
We can still keep the backup archive for the sake of the project's memory

**Comment by agiudiceandrea** [comment]
> I haven't had any need to dig back into the original issue that was copied in github for a great while;

@haubourg, only the issues' descriptions and comments were copied, not the attachments.

See https://lists.osgeo.org/pipermail/qgis-developer/2025-February/067317.html
