### ISSUE TITLE
Add country name to the Sustaining Members

### ISSUE THREAD

**Issue by Xpirix** [qgis/QGIS-Website#424]
### Feature Description

From @andreasneumann 

> Show the country instead of the dates:

![image](https://github.com/user-attachments/assets/cdd0eb20-029a-4269-85e4-cad0355c126f)

**Comment by Xpirix** [comment]
Please find the proposed fix at #428.

Regards.

**Comment by andreasneumann** [comment]
Just to add a bit information why we removed the dates:

- sustaining memberships are per calendar year
- all of the dates are the same as a consequence
- there is a distinction of current and expired sustaining members (past year only (I think))
