### ISSUE TITLE
File wont install, QGIS 3.34 LTR on my Windows 11 laptop

### ISSUE THREAD

**Issue by DMC121316** [qgis/QGIS-Website#434]
### URL

https://qgis.org/download/

### On what type of device(s) did you see this bug?

Desktop

### On which operating system(s) are you seeing the problem?

Windows

### On which browser(s) are you seeing the problem?

Microsoft Edge

### Summary

Lenovo yoga 7i running windows 11. When I click on the file it goes to the windows installer, after a while it pops up with error "not responding"
![Screenshot 2024-09-16 230345](https://github.com/user-attachments/assets/910dab3c-be60-4691-b2f5-cf44ec472c4e)

**Comment by Xpirix** [comment]
@DMC121316 I think it's better to report this issue at https://github.com/qgis/QGIS/issues as it is mostly related to QGIS Desktop
