### ISSUE TITLE
The new version 3.34.11 cannot be downloaded from the QGIS server

### ISSUE THREAD

**Issue by Pippo-90** [qgis/QGIS-Website#439]
### URL

https://qgis.org/downloads/QGIS-OSGeo4W-3.34.11-1.msi

### On what type of device(s) did you see this bug?

Desktop

### On which operating system(s) are you seeing the problem?

Windows

### On which browser(s) are you seeing the problem?

Firefox, Chrome, Microsoft Edge

### Summary

Apparently there is aproblem with the website download.qgis.org. I have tried to connect with both WiFI and Ethernet, however there is a problem with the host.

**Comment by thex1le** [comment]
Cloudflare is reporting an error at download.qgis.org

**Comment by UAVTech78** [comment]
Same issue here along with being able to access new plugins.

**Comment by EP23EP** [comment]
The Version 3.34 LTR cannot be downloaded on my windows laptop. Error code 522 (Host Error) appears every time (firefox, edge, chrome)
