### ISSUE TITLE
Languaje issues - I want to have QGIS in English!!

### ISSUE THREAD

**Issue by alicialedo** [qgis/QGIS-Website#441]
### Tools

Languaje issues - cannot get rid of user interface translation. I want my QGIS in English 

### Summary

Hello. I love QGIS, being used it from over 10 years now.

i´ve just developed the  3.34 version (I was still usin Pi). As I´m now in Spain, it´s recognized the area and self-instaled in Spanish. Thus, suddenly, I cannot properly follow the software. I´ve tried to changed it to English, unsuccessfully, in the "configuration/option" section. Well, that´s how I would translate it, how I read it is "Configuración/Opciones". There´s not an option for me to reject the user interface translation. If I click on override system Locale, nothing happens.  BTW, some of the sentences are in English there.

Thus, it seems I have to uninstall the software, connect to the UK via VPN, then download and install again. Not very handy..

Thanks!!!

**Comment by agiudiceandrea** [comment]
@alicialedo, you need to report the issue to the QGIS Desktop/Server GitHub repository at https://github.com/qgis/QGIS/issues providing all the detailed info requested in the issue report form.

**Comment by haubourg** [comment]
and before this, triple check. I had it work in 3.38 without any issue : 
![image](https://github.com/user-attachments/assets/dcf403dc-0e87-42c1-9a6f-fb189e6311e6)

**Comment by jef-n** [comment]
And to get there in English you can start QGIS from the command line with `qgis -l en`  (eg. from the `OSGeo4W shell`; perhaps `qgis-ltr -l en` depending on the version) and goto Settings/Options and set the override.

**Comment by alicialedo** [comment]
Great thanks! Yes, I had tried the override system before posting, but for an unknown reason didn´t work. that´s my problem.

In the end, I´ve just uninstall and re-install using a different VPN connection and that worked - Probably due to the new installation itself and not the VPN, but for whatever reason, it´s solved.

Thank you very much, really apreciated!!

**Comment by jef-n** [comment]
On Fri, 27. Sep 2024 at 00:27:12 -0700, Alicia Ledo wrote:
> Great thanks! Yes, I had tried the override system before posting, but for an
> unknown reason didn´t work. that´s my problem.
 
> In the end, I´ve just uninstall and re-install using a different VPN
> connection and that worked - Probably due to the new installation itself and
> not the VPN, but for whatever reason, it´s solved.

There are no language specific downloads.  The installer should be identical
no matter how you download it.
 

Jürgen

-- 
Jürgen E. Fischer           norBIT GmbH             Tel. +49-4931-918175-31
Dipl.-Inf. (FH)             Rheinstraße 13          Fax. +49-4931-918175-50
Software Engineer           D-26506 Norden            https://www.norbit.de
QGIS release manager (PSC)  Germany                 IRC: jef on Libera|OFTC

norBIT Gesellschaft fuer Unternehmensberatung und Informationssysteme mbH
Rheinstrasse 13, 26506 Norden
GF: Juergen Fischer, Nils Kutscher HR: Amtsgericht Aurich HRB 100827
Datenschutzerklaerung: https://www.norbit.de/83/

**Comment by alicialedo** [comment]
yes, true. - I (wrongly) tried to explain that was the change in the IP location during installation (not downloading, you´re totally right) what might have worked. Connected from London, I had the QGIS in Eng. as I had wished, whereas with a local (Spanish) connection, I had it in Spanish and the "override system" did not work for an unknown reason.

cheers,
