### ISSUE TITLE
https://qgis.org/debian - https://qgis.org/ubuntu - https://ubuntu.qgis.org/ - ... are down

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Website#446]
### URL

https://qgis.org/debian

### Summary

The repositories of QGIS binaries for Ubuntu\Debian are down. This means it is not currently possible to install/update current versions of QGIS on Debian\Ubuntu systems.

**Comment by Xpirix** [comment]
I see that it has been fixed, closing this.
