### ISSUE TITLE
The Version 3.34 LTR cannot be downloaded on my windows laptop. Error code 522

### ISSUE THREAD

**Issue by EP23EP** [qgis/QGIS-Website#447]
### URL

https://download.qgis.org//downloads/QGIS-OSGeo4W-3.34.11-1.msi

### Type(s) of Problems

Broken Link

### Summary

The Version 3.34 LTR cannot be downloaded on my windows laptop. Error code 522 (Host Error) appears every time (firefox, edge, chrome)

**Comment by dlescano2** [comment]
The same happens with version 3.38. Connection timed out Error code 522

**Comment by jcamilorg** [comment]
Same on Mac files all versions

**Comment by EP23EP** [comment]
Today it could have been downloaded.

But afterwards, when opening QGIS, this error has been displayed:

"Open Sans font installation failed"
Error transferring https://github.com/google/fonts/raw/main/ofl/opensans/OpenSans[wdth,wght].ttf - server replied: Not Found

What can I do?

**Comment by Xpirix** [comment]
@EP23EP 

> "Open Sans font installation failed"
Error transferring [https://github.com/google/fonts/raw/main/ofl/opensans/OpenSans[wdth,wght].ttf](https://github.com/google/fonts/raw/main/ofl/opensans/OpenSans%5Bwdth,wght%5D.ttf) - server replied: Not Found

Does the issue still occur? I think you should report it at https://github.com/qgis/QGIS if it's related to QGIS Desktop
