### ISSUE TITLE
Add a "Contact" link/menu to the footer or the main menu

### ISSUE THREAD

**Issue by elpaso** [qgis/QGIS-Website#451]
### Feature Description

We have  a problem with people writing emails to board@qgis.org (and other qgis email addresses) asking for support.

During the PSC meeting we noticed that there is no "contact" menu on the home page.

We think it would be a good idea to add such a link/menu that points to a page (or maybe a wizard) that allow users to use the right channel to contact the QGIS community members that are most suited to handle the request.

### Reference to Feature

Almost every website has a "contact" menu

**Comment by Xpirix** [comment]
Hi @elpaso 

Please find the proposed fixes for this at #472 and https://github.com/qgis/qgis-uni-navigation/pull/19

Regards.
