### ISSUE TITLE
Wrong display of version substitution

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Website#466]
### URL

https://qgis.org/resources/hub/#documentation

### Type(s) of Problems

Typo

### Summary

In the mentioned page, |version| is not replaced with the actual value (3.40) in the tab title. But the change is done in the texts below

![image](https://github.com/user-attachments/assets/a3a9c670-8388-4b7c-8d7b-3027c8073d32)

**Comment by Xpirix** [comment]
Hi @DelazJ,

Please find the proposed fix at #467

**Comment by DelazJ** [comment]
Thanks @Xpirix

**Comment by Xpirix** [comment]
Sure thing.
