### ISSUE TITLE
error 522 to download mac version

### ISSUE THREAD

**Issue by Tenertine** [qgis/QGIS-Website#468]
### On what type of device(s) did you see this bug?

Desktop

### On which operating system(s) are you seeing the problem?

MacOs

### Other Browser

Opera

### Summary

![Opera Instantané_2024-11-09_164351_download qgis org](https://github.com/user-attachments/assets/17d10421-e10b-429d-8371-2282aaffa92c)

**Comment by paulrollings** [comment]
Yes I have the same issue.

**Comment by jef-n** [comment]
duplicate of #470
