### ISSUE TITLE
Download Error 522

### ISSUE THREAD

**Issue by rubenalbur** [qgis/QGIS-Website#470]
### URL

https://download.qgis.org//downloads/QGIS-OSGeo4W-3.34.12-1.msi

### Type(s) of Problems

Other

### Summary

I am trying to install the CGIS application but when I click on install I get error 522. I've been trying to download it all day. I don't know what I can do so that I don't get the error.
![Captura de pantalla 2024-11-09 161000](https://github.com/user-attachments/assets/3d56e6e5-afcb-4075-aba8-e74cfc7b2335)

**Comment by avikla** [comment]
Same issue on my desktop PC

**Comment by JaviCoder19** [comment]
Same issue. Hope you can solve it soon
