### ISSUE TITLE
QGIS France user group listed twice as sponsor

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Website#475]
### URL

https://qgis.org/funding/membership/members/

### Type(s) of Problems

Sponsor

### Summary

I'm proud that the French user group could sponsor the project at "Large" level, but I don't think this is enough to get mentioned twice in the list 😄 

![image](https://github.com/user-attachments/assets/4b5d0850-0738-4198-adf1-a103b7052829)

**Comment by Xpirix** [comment]
Hi @DelazJ 

Please find the fix for this at #476
