### ISSUE TITLE
the newsfeed url should point to a feed visualisation, not the url of the news itself

### ISSUE THREAD

**Issue by haubourg** [qgis/QGIS-Website#477]
### Summary

The link pointed in this image will use the url of the newsfeed itself.

![image](https://github.com/user-attachments/assets/10bc4db1-22db-41cc-b3a9-6e82683fbe86)

This will not let user read the whole feed entry and redirect to a strange url. The QGIS for peace URL redirects to the code of conduct page for instance. 

my suggestion would be :

- in feed.qgis.org, offer an url endpoint to visualize one entry
- in qgis.org, redirect to this page
- also add a small link "all news" redirecting to feed.qgis.org homepage

@timlinux @Xpirix @anitagraser any opinion here ?

**Comment by Xpirix** [comment]
I agree with this. For now, the link to the feed from the main website is not easy to find. I think it would be useful to add the "All news" link to the navigation bar (inside the "Project" menu, for example).

For the details page for each entry, I'm thinking about the same design as in the feed form. It will show either when clicking on the link on the news bar for qgis.org or from the feed list on feed.qgis.org:

![image](https://github.com/user-attachments/assets/0de0b401-aad8-41b1-91e5-ae2704b4f305)

We are working on the separated Hub, Planet, from the Plugins with a branding update to match the current QGIS.org. Perhaps we should also add the new links once migrated. What do you think?

**Comment by haubourg** [comment]
> We are working on the separated Hub, Planet, from the Plugins with a branding update to match the current QGIS.org. Perhaps we should also add the new links once migrated. What do you think?

we also have our venerable blog.qgis.org hosted on WordPress that partially overlaps newsfeed. I would vote in favor of using Hugo native blogging capabilities, only once the CI will be able to publish on merge. This would imply a content migration too.

**Comment by Xpirix** [comment]
Hi @haubourg 

Please find the proposed fixes for this issue at #489, https://github.com/qgis/qgis-feed/pull/96, and https://github.com/qgis/qgis-uni-navigation/pull/20.

Regards,
