### ISSUE TITLE
Add Event Calendar for QGIS Agenda (from QGIS.org, User Group, etc)

### ISSUE THREAD

**Issue by ismailsunni** [qgis/QGIS-Website#479]
In the QGIS Contributor Meeting in Bratislava, there is an idea to add a calendar in QGIS website to show the agenda around QGIS. It can be the one from QGIS.org/PSC, the User Groups, and others. It was intended to share what user group do, and perhaps can inspire other user group.

Examples frm Python Community
- PyCon events: https://www.python.org/events/python-events/
- Python User Groups: https://www.python.org/events/python-user-group/
- The map of the events: https://lmorillas.github.io/python_events/

**Comment by Xpirix** [comment]
Hi @ismailsunni 
A link to the events page is shown at https://qgis.org/community/organisation/meetings/. It points to https://github.com/qgis/QGIS/wiki.

However, I also think having these event calendars on the Website would be great.
What do you think about harvesting the wiki page to the "Meeting" page?

Cc @timlinux @anitagraser

**Comment by ismailsunni** [comment]
I think that's enough for now. I was thinking to have a calendar for the events from all the user groups, but may be that's too much to maintain.

**Comment by anitagraser** [comment]
Imho user groups should be encouraged to share their events in the feed so users can see them when they launch QGIS. This would reach more users more effectively rather than an event page hidden somewhere in the website
