### ISSUE TITLE
Multiple broken ways to run

### ISSUE THREAD

**Issue by sweco-sedalh** [qgis/QGIS-Website#480]
### Summary

Trying to get the site building in a local development environment (WSL/PyCharm), there seem to be a lot of ways to "run" the site, only some of which are working:

`make dev`/`Dockerfile.dev`: (hasn't been updated since 2022)

```
ERROR 2024/11/21 18:31:59 render of "section" failed: "/app/themes/hugo-bulma-blocks-theme/layouts/_default/list.html:42:3": execute of template failed: template: _default/list.html:42:3: executing "_default/list.html" at <parti
al "footer.html">: error calling partial: "/app/themes/hugo-bulma-blocks-theme/layouts/partials/footer.html:131:22": execute of template failed: template: partials/footer.html:131:22: executing "partials/footer.html" at <readFile (print .Site.Params.commitFile)>: error calling readFile: file does not exist
ERROR 2024/11/21 18:31:59 render of "section" failed: "/app/themes/hugo-bulma-blocks-theme/layouts/_default/list.html:42:3": execute of template failed: template: _default/list.html:42:3: executing "_default/list.html" at <parti
al "footer.html">: error calling partial: "/app/themes/hugo-bulma-blocks-theme/layouts/partials/footer.html:131:22": execute of template failed: template: partials/footer.html:131:22: executing "partials/footer.html" at <readFile (print .Site.Params.commitFile)>: error calling readFile: file does not exist
ERROR 2024/11/21 18:31:59 render of "section" failed: "/app/themes/hugo-bulma-blocks-theme/layouts/_default/list.html:42:3": execute of template failed: template: _default/list.html:42:3: executing "_default/list.html" at <parti
al "footer.html">: error calling partial: "/app/themes/hugo-bulma-blocks-theme/layouts/partials/footer.html:131:22": execute of template failed: template: partials/footer.html:131:22: executing "partials/footer.html" at <readFile (print .Site.Params.commitFile)>: error calling readFile: file does not exist
ERROR 2024/11/21 18:31:59 render of "section" failed: "/app/themes/hugo-bulma-blocks-theme/layouts/_default/list.html:42:3": execute of template failed: template: _default/list.html:42:3: executing "_default/list.html" at <parti
al "footer.html">: error calling partial: "/app/themes/hugo-bulma-blocks-theme/layouts/partials/footer.html:131:22": execute of template failed: template: partials/footer.html:131:22: executing "partials/footer.html" at <readFile (print .Site.Params.commitFile)>: error calling readFile: file does not exist
Error: Error building site: failed to render pages: render of "section" failed: "/app/themes/hugo-bulma-blocks-theme/layouts/people/list.html:24:3": execute of template failed: template: people/list.html:24:3: executing "people/
list.html" at <partial "footer.html">: error calling partial: "/app/themes/hugo-bulma-blocks-theme/layouts/partials/footer.html:131:22": execute of template failed: template: partials/footer.html:131:22: executing "partials/footer.html" at <readFile (print .Site.Params.commitFile)>: error calling readFile: file does not exist
```

`docker-compose.yml`: Seems to be obsolete? (also hasn't been updated since 2022)

VS Code tasks: Presumably working but not relevant when using another IDE

In the end I just ran `hugo server` from the CLI, which works (after realizing that the current version of Hugo isn't working).

I'll create a PR with that instruction as well, but would also like to know if it would be alright to remove `docker-compose.yml`, `Dockerfile.dev` and the commands in the `Makefile`?

**Comment by Xpirix** [comment]
Thanks for reporting this @sweco-sedalh.
It should be okay to remove the docker features as they are deprecated and perhaps not being used anymore.

There is also a way to run the development environment with Nix by running `nix-shell`.  It's not documented yet, but it would be great to have that. I can also submit a PR later for this specific part. Please let me know if this is already part of your suggestion.

**Comment by sweco-sedalh** [comment]
I'm not sufficiently familiar with nix to be able to confidently do anything with it, so I'll leave that to you!

**Comment by haubourg** [comment]
@Xpirix I stumble against the very same error using deb hugo extended package. I tested 0.107.0. 
It is a bit odd that the most straightforward way of running Hugo fails. I run at least 3 other websites with no errors. 

.Site.Params.commitFile searches for a file that exists and is correctly defined in config.toml. 

Any idea how to fix this ?

**Comment by Xpirix** [comment]
Hi @haubourg, I think this feature doesn't exist yet in `v0.107.0`. The website should be built successfully using the `v0.126.1` to `v0.128.1`. I've submitted a PR that updates the README at #488.

However, this will be followed by #487 (Draft PR), which updates the deprecated codes to work with the latest version of Hugo (`v0.139.3`).

**Comment by haubourg** [comment]
ha thanks!  I first started with a 0.139 which I use at work, and it is also broken there because some features are now end of life, and we have a bunch of deprecations pending. 

```
󰈺  ❯ hugo version
hugo v0.139.2-770f548b47b39e6f0fd4da1cc80552024e5829e1+extended linux/amd64 BuildDate=2024-11-23T15:33:51Z VendorInfo=gohugoio
user: regis QGIS-Hugo on  rhaubourg/minor_readme_improvements [!?] is 󰏗 v1.0.0 via  v18.20.4 via  v3.12.3
󰈺  ❯ hugo server
WARN  deprecated: site config key paginate was deprecated in Hugo v0.128.0 and will be removed in a future release. Use pagination.pagerSize instead.
Watching for changes in /data/GITHUB_PERSO/QGIS-Hugo/{content,data,layouts,package.json,static,themes}
Watching for config changes in /data/GITHUB_PERSO/QGIS-Hugo/config.toml
Start building sites …
hugo v0.139.2-770f548b47b39e6f0fd4da1cc80552024e5829e1+extended linux/amd64 BuildDate=2024-11-23T15:33:51Z VendorInfo=gohugoio

WARN  deprecated: resources.ToCSS was deprecated in Hugo v0.128.0 and will be removed in a future release. Use css.Sass instead.
ERROR deprecated: data.GetCSV was deprecated in Hugo v0.123.0 and will be removed in Hugo 0.140.0. use resources.Get or resources.GetRemote with transform.Unmarshal.
Built in 8332 ms
Error: error building site: logged 1 error(s)
```

**Comment by Xpirix** [comment]
Yes, they should be fixed with the upcoming PR. I will perhaps add a version checker and start the development environment with a make command.

**Comment by sweco-sedalh** [comment]
I think it would make a lot of sense to provide a codespaces environment as well (or even primarily, they can still be helpful for setting up locally), that could especially lower the barrier of entry for those contributors who just want to fix a bit of text or so, regardless of proficiency with setting up dev environments etc.

https://docs.github.com/en/codespaces/developing-in-a-codespace/creating-a-codespace-for-a-repository

**Comment by haubourg** [comment]
> I think it would make a lot of sense to provide a codespaces environment as well (or even primarily, they can still be helpful for setting up locally), that could especially lower the barrier of entry for those contributors who just want to fix a bit of text or so, regardless of proficiency with setting up dev environments etc.

I am not sure how codespace could preview a built site like when doing local dev. In my organization, I ended up creating a S3 http bucket on the fly for each merge request, destroyed after two monthes of inactivity, or when merged in master. The MR shows the temporary url so that en users can do a review, push commits, and see a live website after a few seconds. Quite simple and effective

**Comment by sweco-sedalh** [comment]
That sounds like two separate things to me - having an easily accessible development environment and having an easy way to preview PRs. Codespaces are for the later (though they can technically also be used for PR review) but for the later it would probably be more interesting with something like Netlify or Vercel, that create and publish a build on every PR and post the link to it in the PR.
