### ISSUE TITLE
download error for newest QGIS version

### ISSUE THREAD

**Issue by jlitch** [qgis/QGIS-Website#485]
### Type(s) of Problems

Broken Link

### Summary

![Capture](https://github.com/user-attachments/assets/da05b60f-51b8-4923-9fae-88ef3d397312)

alls I get in my downloads folder is Unconfirmed 72955.crdownload, I can't get the latest version of QGIS?!

**Comment by jlitch** [comment]
https://www.qgis.org/download/

**Comment by IamLRBA** [comment]
Hello @jlitch , may i please be assigned to this issue.
Thanks!

**Comment by Xpirix** [comment]
Is the issue still occurring? I think this file extension is for downloads that aren't finished until the end.

**Comment by jlitch** [comment]
yes, I tried twice yesterday, I still can't get the most recent stable version?

**Comment by Xpirix** [comment]
Did you try using a different browser or a download manager? Or do we have that issue from the download server @jef-n ?

**Comment by Xpirix** [comment]
I'm closing this for now. Please don't hesitate to add a comment if you have any news or reopen it if it's related to the download server.
