### ISSUE TITLE
Update sponsor scraper to fetch data from changelog

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS-Website#5]
### Feature Description

Port the logic from here https://github.com/qgis/QGIS-Website/blob/master/.github/workflows/pages.yml#L50 to this project. Sponsors should be created using sponsor archetype
Gallery could go in its own page

**Comment by timlinux** [comment]
Feeds available at https://changelog.qgis.org/en/qgis/members/list/

**Comment by rcoffie** [comment]
Hi @timlinux  am  blocked on this issues .

### Research 
I created a Git Repo that scrap websites and save them in a file by using GH actions  [Repo](https://github.com/rcoffie/gh-action-srape1).

![github action web scrap code](https://user-images.githubusercontent.com/34107104/209842917-b52e644d-98c1-4700-97fd-2989f915d80a.png)

Test for other website pass successfully but that of qgis-feed fail . 

**Scrap result for other website **
![other websites-scrape](https://user-images.githubusercontent.com/34107104/209843127-c562f36a-e756-41fd-afba-096f1afdb68e.png)

**Scrap result for QGIS members feed**
![scrape-qgis-feed](https://user-images.githubusercontent.com/34107104/209843478-41c515f5-a5a6-4902-baa0-fddcaed0a90d.png)

Error message when i run the workflow   **->**  **parse error: Invalid numeric literal at line 1, column 7**.

Logic was based on a blog post by [Simon WiIlison](https://simonwillison.net/2020/Oct/9/git-scraping/).

**Comment by timlinux** [comment]
@rcoffie forget all the actions and other parts and just write from scratch a little python script that downloads the feed and generates a series of files, one per sustaining member. The files written should be hugo markdown with frontmatter as per the examples already under content/gold-sustainers.
