### ISSUE TITLE
Line Rasterize

### ISSUE THREAD

**Issue by settyea** [qgis/QGIS-Website#509]
I cannot rasterize the line using vector conversion in qgis 3.34.12. "ERROR 1: Attempt to create 0x0 dataset is illegal,sizes must be larger than zero. 
ERROR 1: Cannot create C:/Users/Admin/AppData/Local/Temp/processing_cIDeaS/88974d495c9d400f98e5b8a0948e038b/OUTPUT.tif
Process returned error code 1" kept on appearing after I run.

**Comment by Xpirix** [comment]
Dear @settyea , thanks for reporting this.

Please note that this repository is for the QGIS website (https://qgis.org). To report issues related to QGIS desktop, I think it's better to use the core repostitory https://github.com/qgis/QGIS/issues

Regards.
