### ISSUE TITLE
Fine-tune block design

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS-Website#71]
### URL

https://qgis.github.io/QGIS-Hugo/value-proposition/

### Summary

As far as I can see, the design (Figma on the left, current website on the right) asks for

- [ ] Text should be vertically centered (note that the down-arrow/link should not be taken into account when determining the center location)
- [ ] Text on the left should also be horizontally centered
- [ ] Upper case text on the left
- [ ] More padding (something like 2em?)
- [ ] No space between the upper part with the content and the lower part with the link

![image](https://user-images.githubusercontent.com/590385/210023652-ac8b3514-69d6-4b2e-a8f0-8fdae929e60e.png)

- [ ] When there is an image or differently colored title block, the arrow/link should be centered in the colored colored block (rather than centered over the full page width)

![image](https://user-images.githubusercontent.com/590385/210024302-25dbf6b3-ee91-41b7-85ae-0e556ea0226e.png)

**Comment by anitagraser** [comment]
@anniinakovalainen please add any details I may have missed with respect to these blocks

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/212776715-27e83cd4-4bcf-4490-ae01-42d34e2f9a16.png)

**Comment by timlinux** [comment]
Can we close this?

**Comment by anitagraser** [comment]
For my taste, there's not enough "white space" / padding between the text and the box border and between the two text blocks.

![image](https://user-images.githubusercontent.com/590385/212987565-42077e6f-3c59-4556-8da5-8666e322e6c0.png)

**Comment by anitagraser** [comment]
The spacing looks quite ok on a wide screen but when the window is made smaller, there's a jump when the boxes suddenly get even narrower and everything looks squished together. I would prefer much more if the boxes would go full page width at that point. 
![qgis-hugo-1](https://user-images.githubusercontent.com/590385/212988927-83e7d39c-8d38-4910-93f7-70a1b769b9b3.gif)

**Comment by anitagraser** [comment]
Superseded by #135
