### ISSUE TITLE
Remove "Donate!" button

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS-Website#75]
### Summary

In my opinion, the current donate button on the draft website is too visually dominant and adds to the visual clutter. It's larger than the QGIS logo. I prefer the Figma design.

![image](https://user-images.githubusercontent.com/590385/210024802-b4baa246-05bb-45fb-bfa7-1069e8050a5a.png)

**Comment by anniinakovalainen** [comment]
And to add to this, if there is a button, it shouldn't be next to search input field. It can be taken falsely for a search action button. But overall I agree with Anita, I would like a more suttle "support us" approach than a screaming donate button.

**Comment by timlinux** [comment]
Can we discuss this next time we chat? For me I prefer that it is the most visually dominant element - one of the main reasons for me for the site overhaul it to drive funding to the project and I dont think the figma approach stands out enough.

@anniinakovalainen 's concern should be addressed by the refactored search icon behaviour:

![Peek 2023-01-16 22-20](https://user-images.githubusercontent.com/178003/212773860-29bdaf88-d11d-4f77-b778-246f3977e090.gif)

**Comment by anitagraser** [comment]
Superseded by #135

**Comment by timlinux** [comment]
@anitagraser can we close this, or can you clarify why you reopened it? Thanks!

**Comment by anitagraser** [comment]
I'm sure this is outdated
