### ISSUE TITLE
Alter block appearance animation

### ISSUE THREAD

**Issue by anniinaiikkanen** [qgis/QGIS-Website#76]
### Summary

The new block animation is still quite old school and aggressive. The scale change is too drastic and there should be ease-ins and/or outs.

**Comment by anniinakovalainen** [comment]
Actually, I kinda feel like this is not going to work, maybe just drop the block appearance animation all together for now? This is fine tuning and when we don't have a proper skeleton, it's a bit insufficient to be focusing on this. It's like doing a frosting on an unbaked cake.

**Comment by timlinux** [comment]
Animations are disabled by default....I left a flag in there that lets us enable them when and if we want to in the future...
