### ISSUE TITLE
Remove "news QGIS release banner"

### ISSUE THREAD

**Issue by anniinaiikkanen** [qgis/QGIS-Website#77]
### Summary

The banner below the hero image is distracting and quite annoying to be honest. It is in every single page and the placing is wrong. If you want to have this kind of "info banner, alert banner" it should be placed between menu and hero image. Overall I would remove it as it is quite annoying to have in every single page.

![image](https://user-images.githubusercontent.com/51991990/210054844-11ac25d9-5c09-44fa-b0ba-f5de4ff73e9c.png)

**Comment by timlinux** [comment]
Maybe we can have it on the landing page only, but I disagree on removing this completely and prefer it on every page. We need way to call attention to important announcements and the news blocks in the figma mockups are too hidden away at the bottom of the page. Please also note it now looks like this with the branding applied. Let's discuss in the next meetup.

![image](https://user-images.githubusercontent.com/178003/212774857-26a44bfb-c738-4653-9a31-a7b72c28e30e.png)

**Comment by timlinux** [comment]
I also prefer it below the banner than above as we also have (and need) submenus which makes everything look very cluttered:

![image](https://user-images.githubusercontent.com/178003/212775637-5ba29dc5-ec61-4ad0-9a93-81f13148bbe0.png)


versus

![image](https://user-images.githubusercontent.com/178003/212775789-b7fb9d0f-eca8-432c-b084-19ebb429cc1e.png)

or (depending on how we apply the branding) 

![image](https://user-images.githubusercontent.com/178003/212776168-18b5626a-e114-4f33-a45f-1a81c20c9264.png)

**Comment by anitagraser** [comment]
Superseded by #135
